name: CI

on:
  push:

env:
  DATABASE_URL: 'postgres://postgres:postgres@localhost:5432/postgres'
  PGPASSWORD: postgres
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short
  RUSTFLAGS: '-D warnings'

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ secrets.CLEAR_CACHE }}

      - name: Set up rotations table
        run: psql -U postgres -h 127.0.0.1 -d postgres -f sql/rotations.sql

      - name: Format
        run: cargo fmt --all -- --check

      - name: Compile
        run: cargo test --all-features --no-run --locked

      - name: Test
        run: cargo test --all-features -- --nocapture --quiet

      - name: Lints
        run: cargo clippy --all-features
