name: Format

on:
    push:
        branches-ignore:
            - main
    pull_request:
        branches-ignore:
            - main

jobs:
    backend:
        runs-on: ubuntu-latest
        steps:
            - uses: hecrj/setup-rust-action@v1
              with:
                  components: rustfmt
            - uses: actions/checkout@v2
            - name: Check format
              run: cargo fmt --all -- --check
