name: Test

on:
  push:
    branches-ignore:
      - main
      - 'renovate/**'
  pull_request:

env:
  DATABASE_URL: 'postgres://postgres:postgres@localhost:5432/postgres'
  PGPASSWORD: postgres

jobs:
  cargo-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-api-cache-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-api-cache-

      - name: Set up rotations table
        run: psql -U postgres -h 127.0.0.1 -d postgres -f sql/rotations.sql

      - name: Run tests
        run: |
          cargo test --verbose --all
          cargo test --verbose --all --all-features
